myApp.onPageBeforeInit('tasks', function (page) {
    $$('.panel.panel-left .content-block').html(
    '<div class="list-block accordion-list filter">'
    +'<ul>'
     +   '<li class="accordion-item">'
     +   '<a href="" class="item-link item-content">'
     +   '<div class="item-inner">'
     +   '<div class="item-title">Фильтр</div>'
     +   '</div>'
     +   '</a>'
     +   '<div class="accordion-item-content">'
     +   '<div class="list-block filter">'
     +   '<ul>'
     +   '<li>'
     +   '<div class="item-content">'
     +   '<div class="item-inner">'
     +   '<div class="item-title label">Дата от</div>'
    +'<div class="item-input">'
    +    '<input type="date" name="name">'
    +    '</div>'
    +    '</div>'
    +    '</div>'
    +    '</li>'
    +    '<li>'
    +    '<div class="item-content">'
    +    '<div class="item-inner">'
    +    '<div class="item-title label">Дата до</div>'
    +'<div class="item-input">'
    +    '<input type="date" name="name">'
    +    '</div>'
    +    '</div>'
    +    '</div>'
    +    '</li>'
    +    '</ul>'
    +    '</div>'
    +    '</div>'
    +    '</li>'
    +    '</ul>'
    +    '</div>'
        );
});
